version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - tika
      - db
      - elasticsearch
    environment:
      - PYTHONPATH=/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A src.api.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
      - tika
      - db
      - elasticsearch
    environment:
      - PYTHONPATH=/app

  tika:
    image: "apache/tika:latest"
    ports:
      - "9998:9998"

  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_DB: knowledge_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data: